// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swizenaszogesgnjrawa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3aXplbmFzem9nZXNnbmpyYXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQwMzQsImV4cCI6MjA2NTU2MDAzNH0.w331tmv57DJVaHs7H22pMSZKe9f84Bmwx4vaAnJQC8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);